language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
cache: pip
before_install:
 - pip install -r requirements.txt
 - sudo apt-get -qq install gcc gfortran libblas-dev cmake curl
install:
 - ls $TRAVIS_BUILD_DIR
 - python setup.py install
script:
 - cd $TRAVIS_BUILD_DIR/tests
 - python test_travis.py
