language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
cache: pip
before_install:
 - sudo apt-get -qq install gcc gfortran libblas-dev cmake curl
 - pip install -r requirements.txt
install:
 - cd $TRAVIS_BUILD_DIR
 - echo $LD_LIBRARY_PATH
 - pip install .
script:
 - cd $TRAVIS_BUILD_DIR/tests
 - python test_travis.py
