language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
cache: pip
before_install:
 - pip install -r requirements.txt
install:
 - ls $TRAVIS_BUILD_DIR
 - pip install . --user
script:
 - cd $TRAVIS_BUILD_DIR/tests
 - python test_travis.py
